#!/bin/sh

VERSION=$(python -V | grep -Po '(?<=Python )(.+)')
parsedVersion=${VERSION//./}

if [ "$parsedVersion" -ge "380" ]
  then
    pip install numpy
    pip install scipy

  else
    echo "Invalid version of Python"
    echo "Make sure to use Python 3.8.0 or higher"
